# Generated by Django 3.0.1 on 2020-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='auction_items'),
        ),
    ]
