# Generated by Django 3.0.1 on 2020-01-11 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0002_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
