# Generated by Django 3.0.1 on 2020-01-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0003_auto_20200111_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='days',
        ),
    ]
