# Generated by Django 3.0.1 on 2020-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0004_remove_auctionitem_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='viewCount',
            field=models.IntegerField(),
        ),
    ]
