# Generated by Django 3.0.1 on 2020-01-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0005_auto_20200111_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='viewCount',
            field=models.IntegerField(default=1),
        ),
    ]
