# Generated by Django 3.0.1 on 2020-01-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0006_auto_20200111_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='viewCount',
        ),
    ]
