# Generated by Django 3.0.1 on 2020-01-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0009_auto_20200112_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='item_views',
            field=models.IntegerField(default=0),
        ),
    ]
