# Generated by Django 3.0.1 on 2020-01-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0010_auto_20200112_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='item_views',
            new_name='viewCount',
        ),
    ]
