# Generated by Django 3.0.1 on 2020-01-13 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0011_auto_20200113_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='endDate',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.date(2020, 1, 13)),
        ),
    ]
