# Generated by Django 3.0.1 on 2020-01-13 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0012_auto_20200113_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.date(2020, 1, 20)),
        ),
    ]
