# Generated by Django 3.0.1 on 2020-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0013_auctionitem_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='buyNowPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='deliveryCost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startBid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
