# Generated by Django 3.0.1 on 2020-01-19 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0015_auto_20200118_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='nowSaved',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 11, 27, 22, 261442)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 11, 27, 22, 261442)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 11, 27, 22, 261442)),
        ),
    ]
