# Generated by Django 3.0.1 on 2020-01-20 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0016_auto_20200119_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='nowSaved',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 14, 46, 54)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 14, 46, 54)),
        ),
    ]
