# Generated by Django 3.0.1 on 2020-01-20 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0017_auto_20200120_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='now_stored',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 16, 2, 54)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 16, 2, 54)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 16, 2, 54)),
        ),
    ]
