# Generated by Django 3.0.1 on 2020-01-22 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0018_auto_20200120_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 23, 22, 1, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='now_stored',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 23, 22, 1, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 23, 22, 1, tzinfo=utc)),
        ),
    ]
