# Generated by Django 3.0.1 on 2020-02-10 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0019_auto_20200122_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 12, 32, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='now_stored',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 17, 12, 32, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 17, 12, 32, tzinfo=utc)),
        ),
    ]
